// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3xg-i3CS58vFb9RiHwtkILIxfv8uNMhE',
    appId: '1:834086430678:web:5086a3ebfb3bd0c4446677',
    messagingSenderId: '834086430678',
    projectId: 'carerassistant-64205',
    authDomain: 'carerassistant-64205.firebaseapp.com',
    storageBucket: 'carerassistant-64205.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcRwg9zM6H2CiG6uJSUk2oMXXBAw9oKjU',
    appId: '1:834086430678:android:1b64d5c081c0e33a446677',
    messagingSenderId: '834086430678',
    projectId: 'carerassistant-64205',
    storageBucket: 'carerassistant-64205.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxVUFqhkFKvkitOYpk7VUykLPSVXMgQns',
    appId: '1:834086430678:ios:08b6ebce1cf7d632446677',
    messagingSenderId: '834086430678',
    projectId: 'carerassistant-64205',
    storageBucket: 'carerassistant-64205.appspot.com',
    iosBundleId: 'com.quinnd13.carerassistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxVUFqhkFKvkitOYpk7VUykLPSVXMgQns',
    appId: '1:834086430678:ios:08b6ebce1cf7d632446677',
    messagingSenderId: '834086430678',
    projectId: 'carerassistant-64205',
    storageBucket: 'carerassistant-64205.appspot.com',
    iosBundleId: 'com.quinnd13.carerassistant',
  );
}
